# This is a basic workflow to help you get started with Actions

name: ROS

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
  pull_request:
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-humble:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04
    container:
      image: ros:humble
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          path: /ros2_ws/src/scout_ugv_sdk
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y git libasio-dev
      - name: Run colcon build
        run: cd /ros2_ws && /bin/bash -c "source /opt/ros/${ROS_DISTRO}/setup.bash; colcon build"
  build-jazzy:
    # The type of runner that the job will run on
    runs-on: ubuntu-24.04
    container:
      image: ros:jazzy
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          path: /ros2_ws/src/scout_ugv_sdk
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y git libasio-dev
      - name: Run colcon build
        run: cd /ros2_ws && /bin/bash -c "source /opt/ros/${ROS_DISTRO}/setup.bash; colcon build"

